// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("Layout");

function make(_children) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return ReasonReact.createDomElement("div", {
                  className: "o-container o-container--super c-text"
                }, _children);
    });
  return newrecord;
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
