// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Layout$ReactTemplate = require("./layout.bs.js");
var Content$ReactTemplate = require("./content.bs.js");

var component = ReasonReact.statelessComponent("App");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return ReasonReact.element(/* None */0, /* None */0, Layout$ReactTemplate.make(/* array */[
                      React.createElement("div", {
                            className: "header"
                          }),
                      ReasonReact.element(/* None */0, /* None */0, Content$ReactTemplate.make(/* array */[])),
                      React.createElement("div", {
                            className: "footer"
                          })
                    ]));
    });
  return newrecord;
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
