// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Path = require("path");
var $$Array = require("bs-platform/lib/js/array.js");
var $$String = require("bs-platform/lib/js/string.js");

function getDirPath(oldPath, newPart) {
  return Path.normalize(oldPath + (Path.sep + newPart));
}

function mapToFileInfo(path, name) {
  var fullPath = Path.resolve(path, name);
  var stats = Fs.statSync(fullPath);
  return /* record */[
          /* name */name,
          /* fullPath */fullPath,
          /* isFile */+stats.isFile()
        ];
}

function sortByTypeAndName(a, b) {
  if (a[/* isFile */2] === b[/* isFile */2]) {
    return $$String.compare(a[/* name */0], b[/* name */0]);
  } else if (a[/* isFile */2] !== 0) {
    if (b[/* isFile */2] !== 0) {
      return 0;
    } else {
      return 1;
    }
  } else if (b[/* isFile */2] !== 0) {
    return -1;
  } else {
    return 0;
  }
}

function getFilesList(path) {
  var files = $$Array.append(/* array */[/* record */[
          /* name */"..",
          /* fullPath */path,
          /* isFile : false */0
        ]], $$Array.map((function (filename) {
              return mapToFileInfo(path, filename);
            }), Fs.readdirSync(path)));
  $$Array.fast_sort(sortByTypeAndName, files);
  return files;
}

exports.getDirPath = getDirPath;
exports.mapToFileInfo = mapToFileInfo;
exports.sortByTypeAndName = sortByTypeAndName;
exports.getFilesList = getFilesList;
/* fs Not a pure module */
